"""Initial migration

Revision ID: 883f45cf02f1
Revises: 
Create Date: 2025-07-14 05:41:16.224133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '883f45cf02f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_monthly_utilization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('service_line', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('billable_hours', sa.Integer(), nullable=False),
    sa.Column('billable_percent', sa.String(), nullable=False),
    sa.Column('non_billable_hours', sa.Integer(), nullable=False),
    sa.Column('non_billable_percent', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_empid'), type_='unique')
        batch_op.drop_column('service_line')
        batch_op.drop_column('joining_date')
        batch_op.drop_column('empid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empid', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_line', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_employees_empid'), ['empid'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.drop_table('employee_monthly_utilization')
    # ### end Alembic commands ###
