"""Add timesheet_uploads table

Revision ID: c090bf08f66c
Revises: 0aaea2094044
Create Date: 2025-07-18 22:03:39.792840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c090bf08f66c'
down_revision = '0aaea2094044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('payroll_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('employee_number', sa.String(length=50), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.Column('local_day', sa.String(length=20), nullable=True),
    sa.Column('local_start_time', sa.String(length=20), nullable=True),
    sa.Column('local_end_time', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=True),
    sa.Column('job_class', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('service_item', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('approved_status', sa.String(length=50), nullable=True),
    sa.Column('has_flags', sa.Boolean(), nullable=True),
    sa.Column('flag_types', sa.String(length=100), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesheet_uploads')
    # ### end Alembic commands ###
