"""Add empid to employees

Revision ID: 38d37096f1b6
Revises: 883f45cf02f1
Create Date: 2025-07-14 08:43:38.124806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d37096f1b6'
down_revision = '883f45cf02f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empid', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['empid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('empid')

    # ### end Alembic commands ###
