"""Add timesheet_entries, project_rates, project_invoices tables

Revision ID: 39979d1f6ce1
Revises: 38d37096f1b6
Create Date: 2025-07-15 04:53:54.803211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39979d1f6ce1'
down_revision = '38d37096f1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=120), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=120), nullable=False),
    sa.Column('service_item', sa.String(length=120), nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('rate_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timesheet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_email', sa.String(length=120), nullable=False),
    sa.Column('employee_name', sa.String(length=120), nullable=True),
    sa.Column('service_line', sa.String(length=120), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=True),
    sa.Column('project_name', sa.String(length=120), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('service_item', sa.String(length=120), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesheet_entries')
    op.drop_table('project_rates')
    op.drop_table('project_invoices')
    # ### end Alembic commands ###
