"""Add customer relationship to ProjectSetup

Revision ID: 5c6c1c0024bd
Revises: baa8482c76c0
Create Date: 2025-07-22 00:54:34.994574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6c1c0024bd'
down_revision = 'baa8482c76c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_abbreviation', sa.String(length=50), nullable=True),
    sa.Column('project_name_quickbooks', sa.String(length=200), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('customer_bill_contact_name', sa.String(length=200), nullable=True),
    sa.Column('customer_bill_contact_email', sa.String(length=200), nullable=True),
    sa.Column('customer_bill_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_po_number', sa.String(length=100), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('estimated_end_date', sa.Date(), nullable=True),
    sa.Column('project_status', sa.String(length=50), nullable=True),
    sa.Column('as_bid_gross_margin', sa.String(length=50), nullable=True),
    sa.Column('project_estimating_sheet_link', sa.String(length=500), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('employee_contractor_details', sa.JSON(), nullable=True),
    sa.Column('fixed_price_details', sa.JSON(), nullable=True),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('email_recipients', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #with op.batch_alter_table('timesheet_uploads', schema=None) as batch_op:
        #batch_op.alter_column('client_name',
               #existing_type=sa.TEXT(),
               #type_=sa.String(length=200),
               #existing_nullable=True)
        #batch_op.alter_column('project_name',
               #existing_type=sa.TEXT(),
               #type_=sa.String(length=200),
               #existing_nullable=True)
        #batch_op.alter_column('description',
               #existing_type=sa.TEXT(),
               #type_=sa.String(length=255),
               #existing_nullable=True)
        #batch_op.alter_column('service_item',
               #existing_type=sa.TEXT(),
               #type_=sa.String(length=100),
               #existing_nullable=True)
        #batch_op.alter_column('notes',
              # existing_type=sa.TEXT(),
               #type_=sa.String(length=255),
              # existing_nullable=True)
        #batch_op.alter_column('comments',
              # existing_type=sa.TEXT(),
              # type_=sa.String(length=255),
             #  existing_nullable=True)

    # ### end Alembic commands ###


#def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('timesheet_uploads', schema=None) as batch_op:
        #batch_op.alter_column('comments',
               #existing_type=sa.String(length=255),
               #type_=sa.TEXT(),
               #existing_nullable=True)
        #batch_op.alter_column('notes',
               #existing_type=sa.String(length=255),
               #type_=sa.TEXT(),
               #existing_nullable=True)
        #batch_op.alter_column('service_item',
               #existing_type=sa.String(length=100),
               #type_=sa.TEXT(),
               #existing_nullable=True)
        #batch_op.alter_column('description',
               #existing_type=sa.String(length=255),
               #type_=sa.TEXT(),
               #existing_nullable=True)
        #batch_op.alter_column('project_name',
               #existing_type=sa.String(length=200),
               #type_=sa.TEXT(),
               #existing_nullable=True)
        #batch_op.alter_column('client_name',
              # existing_type=sa.String(length=200),
              # type_=sa.TEXT(),
              # existing_nullable=True)

    #op.drop_table('project_setups')
    # ### end Alembic commands ###
